name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION'
      - 'REVISION'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'VERSION'
      - 'REVISION'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the version to use.
        id: var1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the revision to use.
        id: var2
        run: echo "revision=$(cat REVISION)"

      - name: Build Docker image.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ steps.var1.outputs.version }}
          push: false
          tags: dcjulian29/nmap:${{ steps.var1.outputs.version }}.${{ steps.var2.outputs.revision }}-${{ env.GITHUB_SHA }}
