---
name: Release Tool
on:
  push:
    tags:
      - "[0-9].*"

jobs:
  tool:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{ github.workspace }}/go.sum
          go-version-file: ${{ github.workspace }}/go.mod

      - run: |
          $version = Get-Content ${{ github.workspace }}/VERSION
          Write-Host "Image Version: $version"
          echo "IMAGE_VERSION=$version" >> $GITHUB_ENV
      # - name: Grab the version to use.
      #   id: vars
      #   run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - run: echo "${{ env.IMAGE_VERSION }}"
      # - uses: goreleaser/goreleaser-action@v4
      #   with:
      #     args: release
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
      #     IMAGE_VERSION: ${{ steps.vars.outputs.version }}
